# Generated by Django 3.1 on 2020-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passportnumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
