# Generated by Django 3.1 on 2020-08-22 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=uuid.uuid1, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
